"""Add unique constraints on guild_id

Revision ID: be47d79388cd
Revises: 147a24de1e5d
Create Date: 2025-04-23 14:49:37.574529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be47d79388cd'
down_revision: Union[str, None] = '147a24de1e5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_timezone_guild_id', 'Timezone', ['guild_id'])
    op.create_unique_constraint('uq_guilds_guild_id', 'guilds', ['guild_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_guilds_guild_id', 'guilds', type_='unique')
    op.drop_constraint('uq_timezone_guild_id', 'Timezone', type_='unique')
    # ### end Alembic commands ###
