"""Add entry_id_name Column to guilds table

Revision ID: f31bbbf4da54
Revises: be47d79388cd
Create Date: 2025-04-24 04:47:40.888208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f31bbbf4da54'
down_revision: Union[str, None] = 'be47d79388cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guilds', sa.Column('entry_id_name', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guilds', 'entry_id_name')
    # ### end Alembic commands ###
