"""add start and end time column on guilds tables

Revision ID: 0063e63e5c85
Revises: ac3f22cbdc83
Create Date: 2025-04-19 01:16:36.661634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0063e63e5c85'
down_revision: Union[str, None] = 'ac3f22cbdc83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guilds', sa.Column('day', sa.Integer(), nullable=True))
    op.add_column('guilds', sa.Column('start_hour', sa.Integer(), nullable=True))
    op.add_column('guilds', sa.Column('start_minute', sa.Integer(), nullable=True))
    op.add_column('guilds', sa.Column('end_hour', sa.Integer(), nullable=True))
    op.add_column('guilds', sa.Column('end_minute', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guilds', 'end_minute')
    op.drop_column('guilds', 'end_hour')
    op.drop_column('guilds', 'start_minute')
    op.drop_column('guilds', 'start_hour')
    op.drop_column('guilds', 'day')
    # ### end Alembic commands ###
