"""add form_url column on attendance table

Revision ID: ac3f22cbdc83
Revises: 79a6b57fb79c
Create Date: 2025-04-18 22:22:03.719734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac3f22cbdc83'
down_revision: Union[str, None] = '79a6b57fb79c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendances', sa.Column('form_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendances', 'form_url')
    # ### end Alembic commands ###
